spring:
  application:
    name: Config-Dev

eureka:
  instance:
    prefer-id-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
